FROM pytorch/pytorch:latest

RUN pip install pytorch-pretrained-bert
RUN pip install pandas
RUN pip install scikit-learn
RUN pip install imbalanced-learn
RUN pip install jsons

ENV PYTHONPATH /workspace

WORKDIR /workspace